MarcaPonto/Models/ErrorViewModel.cs
using System;

namespace MarcaPonto.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarcaPonto/Controllers/LoginController.cs
using MarcaPonto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MarcaPonto.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
         
    }
}

MarcaPonto/Controllers/OptionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarcaPonto.Controllers
{
    public class OptionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MarcaPonto/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MarcaPonto.Controllers
{
    public class RegisterController : Controller
    {
        // GET: RegisterController
        public ActionResult Index()
        {
            return View();
        }

        // GET: RegisterController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RegisterController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RegisterController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RegisterController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RegisterController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RegisterController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RegisterController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MarcaPonto/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;

namespace MarcaPonto.Controllers
{
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MarcaPonto/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";  
}
   
<div id="outer" class="row">
    <aside class="col-sm-12 col-md-6 col-lg-4">
        <div class="card">
            <article class="card-body">
                <h4 class="card-title mb-4 mt-1">Entrar</h4>
                <form>
                    <div class="form-group">
                        <label>Utilizador</label>
                        <input name="" class="form-control" placeholder="Digite o utilizador" type="text">
                    </div>  
                    <div class="form-group">
                        <a class="float-right" href="#">Esqueci a senha</a>
                        <label>Senha</label>
                        <input class="form-control" placeholder="******" type="password">
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label> <input type="checkbox"> Permanecer conectado </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block" asp-controller="Option" asp-action="Index"> Login </button>
                    </div>
                </form>
            </article>
        </div>  

    </aside>

</div>  

MarcaPonto/Views/Option/Index.cshtml
@{
    ViewData["Title"] = "Definir Opção";  
}
  
<div id="outer" class="row">
    <aside class="col-sm-12 col-md-6 col-lg-4">
        <div class="card">
            <article class="card-body">
                <h4 class="card-title mb-4 mt-1">Escolha uma opção:</h4>
                <form> 
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block" asp-controller="Register" asp-action="Index"> Registar ponto </button>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block" asp-controller="Report" asp-action="Index"> Relatório </button>
                    </div>
                </form>
            </article>
        </div>  

    </aside>

</div>

MarcaPonto/Views/Register/Index.cshtml
<div id="outer" class="row">
    <aside class="col-sm-4 col-lg-6">
        <div class="card">
            <article class="card-body">
                <h4 class="card-title mb-4 mt-1">Registar ponto</h4>
                <form>
                    <div class="form-group">
                        <label for="employee">Funcionário</label>
                        <select class="form-control" id="employee">
                            <option>Gisele Gi</option>
                            <option>Ladrão de gorjeta</option>
                            <option>Gerente</option>
                            <option>Garçon aleatório 1</option>
                            <option>Garçon aleatório 2</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="type">Situação</label>
                        <select class="form-control" id="type">
                            <option>Entrada</option>
                            <option>Saída</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description">Descrição</label>
                        <input type="text" class="form-control" id="description" placeholder="Breve descrição">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Registar </button>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-info btn-block" asp-controller="Option" asp-action="Index">Voltar</button>
                    </div>
                </form>
            </article>
        </div>
    </aside>
</div>

MarcaPonto/Views/Report/Index.cshtml
<div id="outer" class="row">
    <aside class="col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            <article class="card-body">
                <h4 class="card-title mb-4 mt-1">Relatório de Ponto</h4>
                <form>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="employee">Funcionário</label>
                                <select class="form-control" id="employee">
                                    <option>Gisele Gi</option>
                                    <option>Ladrão de gorjeta</option>
                                    <option>Gerente</option>
                                    <option>Garçon aleatório 1</option>
                                    <option>Garçon aleatório 2</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-6 col-lg-3">
                            <div class="form-group">
                                <label for="beginDate">Data início</label>
                                <input id="beginDate" type="date" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6 col-lg-3">
                            <div class="form-group">
                                <label for="endDate">Data fim</label>
                                <input id="endDate" type="date" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-3 col-lg-3 align-self-end">
                            <div class="form-group ">
                                <button type="submit" class="btn btn-primary" asp-controller="Option" asp-action="Index">Buscar dados</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table active table-bordered table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Data</th>
                                            <th class="text-center">Hora</th>
                                            <th class="text-center">Tipo</th>
                                            <th class="text-center">Descrição </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">09:00</td>
                                            <td class="text-center">Entrada</td>
                                            <td class="text-center"></td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">09:50</td>
                                            <td class="text-center">Saída</td>
                                            <td class="text-center">Fumar</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">10:15</td>
                                            <td class="text-center">Entrada</td> 
                                            <td class="text-center">Retorno fumo</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">13:00</td>
                                            <td class="text-center">Saída</td>
                                            <td class="text-center">Almoço</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">14:00</td>
                                            <td class="text-center">Entrada</td>
                                            <td class="text-center">Retorno Almoço</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">15:40</td>
                                            <td class="text-center">Saída</td>
                                            <td class="text-center">Lanche</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">16:00</td>
                                            <td class="text-center">Entrada</td>
                                            <td class="text-center">Retorno Lanche</td>
                                        </tr>
                                        <tr>
                                            <td class="text-center">21/06/2022</td>
                                            <td class="text-center">18:00</td>
                                            <td class="text-center">Saída</td>
                                            <td class="text-center"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row float-right">
                        <div class="col-4">
                            <div class="form-group">
                                <button type="submit" class="btn btn-info " asp-controller="Option" asp-action="Index">Voltar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </article>
        </div>
    </aside>
</div>

MarcaPonto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Regista Ponto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
    </header>
    
    <div class="container">
        <div class="centered-element">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Regista Ponto
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>